# A rig of skills not dependent on a given harness
[rigs.general-skills.riglets]
rigup = ["git-setup", "agent-rig-system", "riglet-creator", "nix-module-system"]
self = [
  "working-with-jj",
  "jj-todo-workflow",
  "nushell-plugin-builder",
  "nushell-usage",
  "package-npm-nix",
  "read-bin-docs",
  "searxng-search",
  "textual-builder",
  "typst-writer",
]

[rigs.claude-rig]
extends.self = "general-skills"
riglets.rigup = ["claude-code"]
riglets.self = ["github-pr-workflow"]

[rigs.copilot-rig]
extends.self = "general-skills"
riglets.rigup = ["copilot-cli"]
# copilot-cli already comes with the GitHub MCP server tools, thus it doesn't need github-pr-workflow

[rigs.cursor-rig]
extends.self = "general-skills"
riglets.self = ["cursor-agent-supervisor", "github-pr-workflow"]
# cursor-agent doesn't have a way to start a sub-agent, but it can be taught to "emulate" this
# by calling itself recursively
