[rigs.claude-code.riglets]
# Include riglets from external flake inputs
rigup = ["agent-rig", "riglet-creator", "nix-module-system"]
# Include riglets from local riglets/ folder
self = [
  # "cursor-agent-supervisor",
  "github-pr-workflow",
  "jj-todo-workflow",
  "nushell-plugin-builder",
  "nushell-usage",
  "package-npm-nix",
  "read-bin-docs",
  "searxng-search",
  "textual-builder",
  "typst-writer",
  "working-with-jj",
]

[rigs.cursor-agent.riglets]
rigup = ["agent-rig", "riglet-creator", "nix-module-system"]
self = [
  "cursor-agent-supervisor",
  "github-pr-workflow",
  "jj-todo-workflow",
  "nushell-plugin-builder",
  "nushell-usage",
  "package-npm-nix",
  "read-bin-docs",
  "searxng-search",
  "textual-builder",
  "typst-writer",
  "working-with-jj",
]

[rigs.copilot-cli.riglets]
rigup = ["agent-rig", "riglet-creator", "nix-module-system"]
self = [
  # "cursor-agent-supervisor",
  # "github-pr-workflow",
  "jj-todo-workflow",
  "nushell-plugin-builder",
  "nushell-usage",
  "package-npm-nix",
  "read-bin-docs",
  "searxng-search",
  "textual-builder",
  "typst-writer",
  "working-with-jj",
]
